## Featured papers

- Pedreira Junior, J. U.; Pitombo, C. S. (2026). Exploring the heterogeneity of changes in work-related mobility patterns throughout the COVID-19 crisis in Brazil: A latent Markov chain analysis of a 3-year panel data. **Travel Behaviour and Society**, v. 42, p. 101160, 2026. [DOI](https://doi.org/10.1016/j.tbs.2025.101160)


- Pedreira Junior, J. U.; Pitombo, C. S. (2024). Unveiling substitution patterns of work trips by teleworking and their associations with physical and virtual accessibility in the Brazilian COVID-19 crisis. **Travel Behaviour and Society**, v. 34, p. 100657 [DOI](https://doi.org/10.1016/j.tbs.2023.100657)


- de Moraes Tavares, A. L., Furlan, A. P., Fabbri, G. T. P., & Pedreira Junior, J. U. (2025). Soil-aggregate-cement mixtures for base pavement layers: A strength and stiffness characterization. **Transportation Geotechnics**, 50, 101456. [DOI](https://doi.org/10.1016/j.trgeo.2024.101456)


- Suzuki Goshima, C. Y., Dias, V. C., Pedreira Junior, J. U., & Pitombo, C. S. (2023). Relationships between teleworking and travel behavior in the Brazilian COVID-19 crisis. **Future Transportation**, 3(2), 739-767. [DOI](https://doi.org/10.3390/futuretransp3020043)


- Louro, T. V., Pedreira Junior, J. U., Gardin, G. T. D. O., & da Silva Junior, C. A. P. (2023). Factors influencing lateral distance and speed of motorized vehicles overtaking bicycles. **Transportation Research Record**, 2677(7), 51-61. [DOI](https://doi.org/10.1177/03611981221150926)


- Pedreira Junior, J. U., Rodrigues da Silva, A. N., & Pitombo, C. S. (2022). Car-free day on a university campus: determinants of participation and potential impacts on sustainable travel behavior. **Sustainability**, 14(6), 3427. [DOI](https://doi.org/10.3390/su14063427)


- Pedreira Junior, J. U., Galindo, E. P., Batista, A. H., Pitombo, C. S., & Rodrigues da Silva, A. N. (2022). The panorama of public officials’ meeting trips after the COVID-19 pandemic: Impact level, recovery, and prospects. **Frontiers in Future Transportation**, 3, 972133. [DOI](https://doi.org/10.3389/ffutr.2022.972133)


- Pedreira Junior, J. U., Assirati, L., & Pitombo, C. S. (2021). Improving travel pattern analysis with urban morphology features: a panel data study case in a Brazilian university campus. **Case Studies on Transport Policy**, 9(4), 1715-1726. [DOI](https://doi.org/10.1016/j.cstp.2021.07.019)

## Preprints
- Pedreira Junior, J. U. P., Louro, T. V., de Assis, L. B. M., & Brito, P. L. (2025). Measuring land-use mix with address-level census data. **engrxiv**. [DOI](https://doi.org/10.31224/5975)


- Pedreira Junior, J. U., do Nascimento, A. N., & de Oliveira Fontes, C. H. (2019). Improving Strategic Decision-Making in a Closed-Loop Rail Network with Hybrid Simulation-Optimization Modeling. **preprints.org**. [DOI](DOI:10.20944/preprints201905.0312.v1)


## Featured conference proceedings
- Assis, L. B. M., Pedreira Junior, J. U., Monari, M., Segantine, P. C. L., Amado, M. J. N. P. (2025). **Mapping healthcare accessibility in São Carlos-SP: A 2-Step Floating Catchment Area approach for accessibility analysis**. In: XXI Simpósio Brasileiro de Sensoriamento Remoto, 2025, Salvador. Anais do XXI Simpósio Brasileiro de Sensoriamento Remoto, v. 1. p. 1-5.


- Pedreira Junior, J. U., Assis, L. B. M., Louro, T. V. (2025). **Cycling under pressure: the role of traffic stress in limiting urban job accessibility by bicycle**. In: 39º Congresso de Pesquisa e Ensino em Transportes (ANPET), Goiânia-GO. Anais do 39º Congresso de Pesquisa e Ensino em Transportes (ANPET), 2025, p. 1-5.


- Louro, T. V., Assis, L. B. M., Pedreira Junior, J. U., Cunha, A. L., Geurs, K. (2025). **Job accessibility in the 15-minute city? a comparative analysis of walking, cycling, and e-bikes in four Brazilian cities**. In: 39º Congresso de Pesquisa e Ensino em Transportes (ANPET), Goiânia-GO. Anais do 39º Congresso de Pesquisa e Ensino em Transportes (ANPET), 2025. v. 1. p. 1-5.


- Assis, L. B. M., Pedreira Junior, J. U., Louro, T. V., Segantine, P. C. L., Amado, M. J. N. P. (2025). **Benchmarking the X-minute city: a multi-city assessment of primary health care accessibility from a socio-spatial inequality perspective**. In: 39º Congresso de Pesquisa e Ensino em Transportes (ANPET),  Goiânia-GO. Anais do 39º Congresso de Pesquisa e Ensino em Transportes (ANPET), 2025. v. 1. p. 1-5.

- Sgura, M., Pedreira Junior, J. U., Pedrassoli, J. C., Oliveira-Esquerre, K. (2025). **Street network susceptibility to flooding based on the Height Above the Nearest Drainage (HAND) model: a case study in Salvador, Brazil**. In: 39º Congresso de Pesquisa e Ensino em Transportes (ANPET), Goiânia-GO. Anais do 39º Congresso de Pesquisa e Ensino em Transportes (ANPET), 2025. v. 1. p. 1-5.

## Books, chapters and technical reports

- Rodrigues da Silva, A. N., Pitombo, C. S., Pedreira Junior, J. U., Ciriaco, T. G. M., & Costa, C. S. (2023). Changes in mobility and challenges to the transport sector in Brazil due to COVID-19. In **Transportation amid pandemics** (pp. 105-118). Elsevier. [DOI](https://doi.org/10.1016/B978-0-323-99770-6.00010-7)


- Pedreira Junior, J. U., Chaves, J. N., & de Souza Santos, L. A. (2019). Developing a Ride Comfort Monitoring System from Scratch: An Experience in a Suburban Railway [J]. **Sustainable Rail Transport**, 19-36. [DOI](https://doi.org/10.1007/978-3-319-78544-8_2)


